spring:
  application:
    name: SuperFolio
    version: 1.0
    group: superfolio
  aop:
    auto: true
  codec:
    log-request-details: true
    max-in-memory-size: 2MB
  lifecycle:
    timeout-per-shutdown-phase: 30s
  data:
    redis:
      port: 6379
      url: "redis://localhost:6379"
      host: localhost
      database: 0
  cache:
    type: none
  mvc:
    log-request-details: true
    problemdetails:
      enabled: true
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"
  gson:
    date-format: ${spring.mvc.format.date-time}
    pretty-printing: on
    strictness: lenient
  jackson:
    date-format: ${spring.mvc.format.date-time}
    default-leniency: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: "*/*"
    min-response-size: 2KB
  error:
    include-message: always
    whitelabel:
      enabled: false
  forward-headers-strategy: framework
  servlet:
    application-display-name: ${spring.application.name}
    context-path: /superfolio
    encoding:
      charset: UTF-8

logging:
  threshold:
    console: TRACE
    file: TRACE
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} %5p [${spring.application.name:CommVault},%X{traceId:-},%X{spanId:-}] %clr([%level]){magenta} %c{1.6} [%t] %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %5p [${spring.application.name:CommVault},%X{traceId:-},%X{spanId:-}] %-5level %logger{36} - %msg%n"
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
  charset:
    console: UTF-8
  include-application-group: true
  include-application-name: true


info:
  app:
    name: "@project.description@"
    version: "@project.version@"
    author: "@project.organization.name@"
    license: "@project.licenses[0].name@"
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"

springdoc:
  cache:
    disabled: false
  show-actuator: false
  remove-broken-reference-definitions: true
  writer-with-default-pretty-printer: true
  packages-to-scan: com.shortthirdman.superfolio.controller
  use-fqn: true
  enable-spring-security: false
  api-docs:
    enabled: true
    path: /api-docs
    version: openapi-3-1
    resolve-schema-properties: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    showCommonExtensions: true
    query-config-enabled: false

management:
  httpexchanges:
    recording:
      enabled: true
      include: "*"
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    env:
      show-values: always
    health:
      probes:
        enabled: true
      group:
        custom:
          show-components: always
          show-details: always
    shutdown:
      access: unrestricted
    startup:
      access: unrestricted
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: openapi, swagger-ui, prometheus, *
    access:
      default: unrestricted